#!/bin/bash
set -e

echo "           INFLUX_CONFIGS_PATH: $INFLUX_CONFIGS_PATH "
echo "                   INFLUX_HOST: $INFLUX_HOST"
echo "  DOCKER_INFLUXDB_INIT_USER_ID: $DOCKER_INFLUXDB_INIT_USER_ID"
echo "   DOCKER_INFLUXDB_INIT_ORG_ID: $DOCKER_INFLUXDB_INIT_ORG_ID"
echo "DOCKER_INFLUXDB_INIT_BUCKET_ID: $DOCKER_INFLUXDB_INIT_BUCKET_ID"