services:
  nginx:
    image: tomcat:10.1.19
    ports:
      - 8080:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
    environment:
      TZ: Asia/Shanghai
    restart: on-failure
