services:
  v2ray:
    image: v2fly/v2fly-core:v5.16.1
    environment:
      TZ: Asia/Shanghai
    ports:
      - 10808:10808
      - 10809:10809
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: 
      - "run"
      - "-c"
      - "/etc/v2ray/config.json"
    restart: always