services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-29T01-20-47Z
    environment:
      TZ: Asia/Shanghai
      MINIO_CONFIG_ENV_FILE: /etc/minio.env
      MINIO_SERVER_URL: http://127.0.0.1:9000
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data-01:/data-1
      - ./data-02:/data-2
      - ./data-03:/data-3
      - ./data-04:/data-4
      - ./minio.env:/etc/minio.env
    restart: always
    command:
      ["minio","server","--console-address", ":9001", "-address", ":9000"]
