services:
  mongo:
    image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./backup:/data/backup
    environment: 
      TZ: Asia/Shanghai
      MONGODB_INITDB_ROOT_USERNAME: mongo
      MONGODB_INITDB_ROOT_PASSWORD: mongo
    user: root
    command: --wiredTigerCacheSizeGB 10.0
    restart: always
