services:
  mongo:
    image: mongo:7.0.1
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./backup:/data/backup
    environment: 
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: testing
    command: --wiredTigerCacheSizeGB 10.0
    restart: always
