services:
  nginx:
    image: nginx:1.25.2
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    environment:
      TZ: Asia/Shanghai
      NGINX_HOST: 
      NGINX_PORT: 80
    restart: on-failure
