services:
  mariadb:
    image: mariadb:11.8.2
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: localhost
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/data/backup
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: on-failure
