services:
  mysql:
    image: mysql:8.4.2
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: localhost
      MYSQL_RANDOM_ROOT_PASSWORD: YES
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/data/backup
      - ./conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: on-failure
