services:
  mysql:
    image: mysql:8.2.0
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/data/backup
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always