services:
  base:
    image: base:12.8
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./before:/init/before
      - ./after:/init/after
    restart: on-failure