services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/data/backup
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./initdb.d/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.utf8
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=zh-CN"
      POSTGRES_PASSWORD: postgres
    command:
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    shm_size: 1GB
    restart: on-failure