services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/data/backup
      - ./testing.sql:/docker-entrypoint-initdb.d/testing.sql
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.utf8
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=zh-CN"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command:
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
    shm_size: 1GB
